### PR TITLE
Add Kazakh translation

### PR DESCRIPTION
**Pull request by crayxt**
Please review. Requires UTF-8-capable font.

### CODE REVIEW

**Comment by crayxt** [comment]
Ping

**Comment by philmmanjaro** [comment]
Well, just the translation won't cut it. You have also include it into the [menu](https://github.com/manjaro/artwork-gfxboot/blob/master/src/dia_lang.inc) ...

**Comment by crayxt** [comment]
@philmmanjaro Dear Philip, is it any good now?

**Comment by philmmanjaro** [comment]
Seems like it. I've to build a new set of binaries to test it though.

**Comment by crayxt** [comment]
@philmmanjaro Hi I just tested manjaro-xfce-16.10.2-stable-x86_64.iso and it seems like Kazakh is not in boot menu.

**Comment by crayxt** [comment]
https://github.com/manjaro/artwork-gfxboot/pull/11

**Pull request merged**
